spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    datasource:
      url: jdbc:postgresql://localhost:5432/ticketservice_db
      username: my_user
      password: my_password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

    redis:
      host: localhost
      port: 6379


  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG
